### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [wenxin-wang/PulseDroidRtp#4]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by wenxin-wang** [comment]
Thank you for the kind notice! I will upload a screenshot after #3 is resolved, since that issue is related to display.
