### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [wenxin-wang/PulseDroidRtp#5]
Ref: https://f-droid.org/wiki/index.php?title=me.wenxinwang.pulsedroidrtp/lastbuild_2&oldid=285173

**Comment by wenxin-wang** [comment]
Thank you for the kind notice! Fixed in  v1.0.3, see https://github.com/wenxin-wang/PulseDroidRtp/commit/183af49296f29862f810f47ca474137371b180c7
