### ISSUE TITLE
App is not requesting android permissions

### ISSUE THREAD

**Issue by RamoxCode** [wenxin-wang/PulseDroidRtp#6]
![Screenshot_20210123-170348.png](https://user-images.githubusercontent.com/58784631/105607126-632bde00-5d9d-11eb-974a-c994f5bc0418.png)

**Comment by wenxin-wang** [comment]
This app only requires network usage, and seems that this permission is always granted with recent Android, so maybe it's not the cause of the problem you are having. Is the app not playing music? If so, can you provide a screenshot of the app after you pressed `Start`?

**Comment by wenxin-wang** [comment]
Close for now. Feel free to reopen the issue if you cannot use the app.
