### ISSUE TITLE
非常棒的项目，可以更完善一些吗?

### ISSUE THREAD

**Issue by qbladea** [wenxin-wang/PulseDroidRtp#9]
我正在使用闲置的安卓手机当作我局域网内的公用通知喇叭
但是这个程序的后台经常被结束，而且无法开机自动启动.

可以加入以下功能吗:

* 开机自动启动
* 在通知栏常驻(避免被清理后台程序)

**Comment by wenxin-wang** [comment]
v1.0.4 提供了这两个功能，有机会可以尝试下

**Comment by wenxin-wang** [comment]
如果仍有问题，欢迎重开这个 issue。
